### ISSUE TITLE
Firebase is undefined

### ISSUE THREAD

**Issue by Znow** [KallynGowdy/angular2-firebase#5]
Following your guidelines, and implementing it, like done in the demo app, i'm getting:

![image](https://cloud.githubusercontent.com/assets/265719/12477024/601a89d6-c02d-11e5-8ed5-1134d746b484.png)

**Comment by KallynGowdy** [comment]
Make sure that you are including the [Firebase JavaScript SDK](https://www.firebase.com/docs/web/quickstart.html) in your project. 
As far as I know, the only error that would cause Firebase to be undefined would be not including the proper script tag before the Angular 2 app is loaded.

This is the tag that should be included in your `index.html` somewhere before the boot file is imported by System.js

``` html
<script src="https://cdn.firebase.com/js/client/2.3.2/firebase.js"></script>
```

**Comment by Znow** [comment]
Hi @KallynGowdy - Thanks for your response. Wouldn't I be able to just install the npm package for firebase?

Kind regards

**Comment by KallynGowdy** [comment]
@Znow Depending on where you are running Angular 2, then yes. 

If you are running Angular 2 code on a Node.js server, then all you need to do is install the npm package and use `require`:

``` TypeScript
var Firebase = require('firebase');

bootstrap(MyAppComponent, [
    provide(FirebaseService, {useFactory: () => 
        new FirebaseService(new Firebase('https://YOUR-FIREBASE-URL.firebaseio.com/')))})
]);
```

Otherwise, if you are running Angular 2 code in a web browser (which is the most common way to run Angular 2), then you need to include the script tag in the `index.html`:

``` html
<script src="https://cdn.firebase.com/js/client/2.3.2/firebase.js"></script>

<script>
// After including firebase, configure and import your scripts using System.js
System.config({ ... });
System.import(...);
</script>
```

The Firebase script will load the Firebase object as a global, which will then make the code work.

**Comment by KallynGowdy** [comment]
@Znow I'm going to close this issue as I have not heard any feedback on my latest suggestion. If you still need assistance with this problem, feel free to comment and I will reopen the issue. Thanks!
